name: Download Twitch Stream

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Twitch Stream URL'
        required: true
        default: 'https://www.twitch.tv/piratesoftware'
      maxTime:
        description: 'maxLength'
        required: true
        default: "3600"
      bitrate:
        description: 'Desired bitrate (e.g., 6000k for 6000 kb/s)'
        required: false
        default: '6000k'

      resolution:
        description: 'Desired resolution (e.g., 1920x1080)'
        required: false
        default: 'res:1280'

        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: python -m pip install --upgrade yt-dlp

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Extract Stream Title
      id: extract-title
      run: echo "STREAM_TITLE=$(yt-dlp --get-title ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV

    - name: Sanitize Stream Title
      run: |
        echo "SANITIZED_TITLE=$(echo $STREAM_TITLE | sed 's/[":<>|*?\\/\r\n]//g')" >> $GITHUB_ENV
        
    - name: Extract m3u8 URL
      id: extract-m3u8
      run: |
        echo "M3U8_URL=$(yt-dlp --no-download --format 'best[protocol=m3u8]/best' -g ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV
        echo "M3U8_URL=$M3U8_URL" >> $GITHUB_OUTPUT  # For debugging

    - name: Restream with FFmpeg
      run: |
        VBR="${{ github.event.inputs.bitrate }}"
        FPS="30"
        QUAL="medium"
        YOUTUBE_URL="rtmp://a.rtmp.youtube.com/live2/"
        KEY="${{ secrets.STREAM_KEY }}"
        RESOLUTION="${{ github.event.inputs.resolution }}"
        MAX_TIME=${{ github.event.inputs.maxTime }}
        
        ffmpeg -re -i "$M3U8_URL" \
               -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
               -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k \
               ${RESOLUTION:+ -vf "scale=${RESOLUTION##*:}:-1"} \
               -t "$MAX_TIME" -f flv "$YOUTUBE_URL/$KEY"
